version: "3.8"

services:
  rust-app:
    build:
      context: .
      dockerfile: ./docker/rust/Dockerfile
    volumes:
      - .:/usr/src/rust-app
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
