version: "3.8"

services:
  rust-app:
    build:
      context: .
      dockerfile: ./rust/Dockerfile
    volumes:
      - ..:/develop
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
  cargo:
    image: rust:latest
    working_dir: /develop
    volumes:
      - ..:/develop
